name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yaml'
      - 'scripts/requirements.txt'

jobs:
  devcontainer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          build-args: REPO=superspreader
          push: true
          target: development
          tags: ghcr.io/kestrel-labs/superspreader:development
          cache-from: type=gha
          cache-to: type=gha,mode=max
